### ISSUE TITLE
Deprecated Code

### ISSUE THREAD

**Issue by GrahamCampbell** [Zeichen32/GitLabApiBundle#10]
Line 97 of `Zeichen32GitLabApiExtension.php` calls the deprecated `create` method:

```
            $definition->setFactory(array('Gitlab\Client', 'create'));
```

Instead, `new Client` should be used, followed by a call to `setUrl`.

**Comment by Zeichen32** [comment]
Hey, thanks for your contribution! I will check your PRs and merge them in the next few days. 👍

**Comment by Zeichen32** [comment]
Changes merged to master :)
