### ISSUE TITLE
No HTTPlug clients found

### ISSUE THREAD

**Issue by adamfrost839** [Zeichen32/GitLabApiBundle#15]
Running v4.0.1 on symfony 3.4.x
I've added php-http/guzzle6-adapter to composer but still getting this error:

**No HTTPlug clients found. Make sure to install a package providing "php-http/client-implementation". Example: "php-http/guzzle6-adapter".**

How do I get it to recognize this client?

**Comment by Zeichen32** [comment]
This error message comes from the Library. Do you already had a look in the PHP Gitlab Library in the correct version:
https://github.com/GitLabPHP/Client/tree/9.19.2

If nothing work, you can configure a client in your service yaml and use the http_client configuration option to let the bundle use this http client.

**Comment by GrahamCampbell** [comment]
You need to also install `http-interop/http-factory-guzzle:^1.0`.

**Comment by GrahamCampbell** [comment]
> I've added php-http/guzzle6-adapter to composer but still getting this error:

Did you run `composer update`?

**Comment by adamfrost839** [comment]
> You need to also install http-interop/http-factory-guzzle:^1.0

This solved the problem. Maybe it should be mentioned in readme, as it's not obvious...

**Comment by Zeichen32** [comment]
In the latest version of this bundle we no longer use the guzzle adapter and use the symfony http client.

@GrahamCampbell  But if this is required we should update the library docs for the 9.19 too?
