### ISSUE TITLE
Cannot unpack array with string keys         

### ISSUE THREAD

**Issue by TheRatG** [Zeichen32/GitLabApiBundle#16]
In ResultPager.php line 81:
                                                           
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Cannot unpack array with string keys                     
                                                           

Exception trace:
  at /home/vagrant/www/wwwfxbo/vendor/m4tthumphrey/php-gitlab-api/src/ResultPager.php:81
 Gitlab\ResultPager->fetch() at /home/vagrant/www/wwwfxbo/vendor/m4tthumphrey/php-gitlab-api/src/ResultPager.php:122
 Gitlab\ResultPager->fetchAllLazy() at n/a:n/a
 iterator_to_array() at /home/vagrant/www/wwwfxbo/vendor/m4tthumphrey/php-gitlab-api/src/ResultPager.php:105
 Gitlab\ResultPager->fetchAll() at /home/vagrant/www/wwwfxbo/src/Command/GitLab/DeletePipelinesCommand.php:54
 App\Command\GitLab\DeletePipelinesCommand->execute() at /home/vagrant/www/wwwfxbo/vendor/symfony/console/Command/Command.php:255

**Comment by TheRatG** [comment]
![Screenshot 2020-12-11 at 16 59 47](https://user-images.githubusercontent.com/1580318/101918653-48791d80-3bd2-11eb-9c99-144b9bc1cdc7.png)

with `array_values($parameters)` it works fine

**Comment by Zeichen32** [comment]
This bundle only register the Gitlab Client in Symfony, so please open an issue in the GitLabPHP Repository with a reference to this issue:
https://github.com/GitLabPHP/Client/issues

**Comment by TheRatG** [comment]
@Zeichen32 thanks for link and sorry for disturb, I was unattentive
