### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by prgrssm** [Zeichen32/GitLabApiBundle#17]
Are there any plans for PHP 8 support? Thx!

**Comment by Zeichen32** [comment]
@prgrssm  Sorry for the late response. I am open for a PR. I think this should not complicated to support PHP8

**Comment by endroid** [comment]
Let's start by allowing PHP 8 :) https://github.com/Zeichen32/GitLabApiBundle/pull/18

**Comment by GrahamCampbell** [comment]
NB Upstream is now in the 11.x series. 10.x is now only receiving security fixes.

**Comment by Zeichen32** [comment]
> NB Upstream is now in the 11.x series. 10.x is now only receiving security fixes.

Are their any braking changes between the 11 und 10 version? So that we need a new major version?

**Comment by GrahamCampbell** [comment]
Yes, there are. Most notably, the model's API (deprecated in 10.x) has been deleted. The reason for this is that it has become massively out of date and many parts of it unusable, and nobody was willing to maintain it, so it has been dropped.

Other breaking changes are listed on the change log, but are unlikely to impact anyone.

**Comment by Zeichen32** [comment]
Okay, thanks for the explanation!

**Comment by endroid** [comment]
Clear @GrahamCampbell then that is something for later and outside the scope of the PHP 8 upgrade. I will revert to 10.3 for now so that there should be no breaking changes.

**Comment by prgrssm** [comment]
Ok, thx guys. It can be closed now.
