### ISSUE TITLE
Child config error 

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [Zeichen32/GitLabApiBundle#25]
Hi all, I am trying to install into my project this library.
I have Symfony 6 and when I try to install this lib via composer I get this error:

```
 The child config "clients" under "zeichen32_git_lab_api" must be configured
```

How can I solve it?

Thanks.

**Comment by Zeichen32** [comment]
After the setup you must configure your client. See step 3 in the setup guid.
https://github.com/Zeichen32/GitLabApiBundle#step-3-configure-zeichen32gitlabapibundle

**Comment by AlessandroMinoccheri** [comment]
The problem @Zeichen32 is when I run `composer require zeichen32/gitlabapibundle` not when I use it. So I have to configure it before install it?

**Comment by Zeichen32** [comment]
Yes you can configure it before installation or use:

```bash
composer require zeichen32/gitlabapibundle --no-scripts
```

Anyway, the installation without --no-scripts is also successfully, only the symfony cache:clear command that runs after composer require is failing because of the missing configuration.
