### ISSUE TITLE
Getting an error while doing composer update

### ISSUE THREAD

**Issue by fahimghl** [Zeichen32/GitLabApiBundle#7]
In ArrayNode.php line 228:
                                                                               
  The child node "clients" at path "zeichen32_gi_lab_api" must be configured.

**Comment by Zeichen32** [comment]
Please try to configure the clients property or provide more informations like your current configuration, symfony version etc.

**Comment by fahimghl** [comment]
Hi, thanks for replying ! it was indentation error I think which is fixed now. Nor I am running into another error! 

Service "gitlab_api" not found: even though it exists in the app's container, the container inside "App\Controller\ReleaseRequestController" is a smaller service locator that only knows about the "form.factory", "http_kernel", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "serializer", "session" and "twig" services. Try using dependency injection instead.

This the code in one of the controllers

$api = $this->get('gitlab_api');        
$issues = $api->api('issues')->all(1);        
var_dump ($issues);

**Comment by fahimghl** [comment]
I had to extend myController with Controller instead of Abstract controller in order to get his working.
